name: build

on:
  push:
    branches: [ master ]
    paths-ignore: [ '*.md' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ '*.md' ]

env:
  CARGO_TERM_COLOR: always
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Resume cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-build
    - name: Install stable Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
